"""
Project Templates
Definicje template'ów dla różnych typów projektów
"""
from typing import Dict, List, Any
from dataclasses import dataclass, field


@dataclass
class ProjectTemplate:
    """Template projektu"""
    id: str
    name: str
    description: str
    tech_stack: str
    project_type: str
    files: List[Dict[str, str]] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    env_vars: List[str] = field(default_factory=list)
    recommended_components: List[str] = field(default_factory=list)


# FastAPI REST API Template
FASTAPI_API_TEMPLATE = ProjectTemplate(
    id="fastapi-api",
    name="FastAPI REST API",
    description="Production-ready REST API with FastAPI",
    tech_stack="python_fastapi",
    project_type="api",
    files=[
        {
            "path": "src/__init__.py",
            "content": ""
        },
        {
            "path": "src/main.py",
            "content": '''"""Main FastAPI Application"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager

from src.config import settings
from src.api import router as api_router


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    print(f"Starting {settings.APP_NAME}")
    yield
    # Shutdown
    print("Shutting down...")


app = FastAPI(
    title=settings.APP_NAME,
    description=settings.APP_DESCRIPTION,
    version=settings.APP_VERSION,
    lifespan=lifespan
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(api_router, prefix="/api/v1")


@app.get("/")
async def root():
    return {"name": settings.APP_NAME, "version": settings.APP_VERSION}


@app.get("/health")
async def health():
    return {"status": "healthy"}
'''
        },
        {
            "path": "src/config.py",
            "content": '''"""Application Configuration"""
from pydantic_settings import BaseSettings
from typing import List


class Settings(BaseSettings):
    APP_NAME: str = "OneDay API"
    APP_DESCRIPTION: str = "Generated by OneDay.run"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False
    
    DATABASE_URL: str = "sqlite:///./app.db"
    
    CORS_ORIGINS: List[str] = ["*"]
    
    class Config:
        env_file = ".env"


settings = Settings()
'''
        },
        {
            "path": "src/api/__init__.py",
            "content": '''"""API Router"""
from fastapi import APIRouter

router = APIRouter()


@router.get("/items")
async def list_items():
    return {"items": []}


@router.post("/items")
async def create_item(item: dict):
    return {"item": item, "id": 1}
'''
        },
        {
            "path": "requirements.txt",
            "content": '''fastapi>=0.100.0
uvicorn[standard]>=0.23.0
pydantic>=2.0.0
pydantic-settings>=2.0.0
python-dotenv>=1.0.0
sqlalchemy>=2.0.0
'''
        },
        {
            "path": "Dockerfile",
            "content": '''FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
'''
        },
        {
            "path": ".env.example",
            "content": '''APP_NAME=MyAPI
DEBUG=false
DATABASE_URL=sqlite:///./app.db
'''
        },
        {
            "path": ".gitignore",
            "content": '''__pycache__/
*.py[cod]
.env
.venv/
venv/
*.db
.pytest_cache/
'''
        },
        {
            "path": "README.md",
            "content": '''# OneDay API

Generated by OneDay.run Platform.

## Quick Start

```bash
pip install -r requirements.txt
uvicorn src.main:app --reload
```

## API Docs

- Swagger: http://localhost:8000/docs
- ReDoc: http://localhost:8000/redoc
'''
        }
    ],
    dependencies=["fastapi", "uvicorn", "pydantic", "sqlalchemy"],
    env_vars=["DATABASE_URL", "DEBUG"],
    recommended_components=["auth-fastapi-jwt", "db-sqlalchemy-base", "api-crud-base"]
)


# Next.js Dashboard Template
NEXTJS_DASHBOARD_TEMPLATE = ProjectTemplate(
    id="nextjs-dashboard",
    name="Next.js Dashboard",
    description="Modern dashboard with Next.js and Tailwind",
    tech_stack="react_next",
    project_type="dashboard",
    files=[
        {
            "path": "package.json",
            "content": '''{
  "name": "oneday-dashboard",
  "version": "1.0.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "tailwindcss": "3.3.0",
    "autoprefixer": "10.4.0",
    "postcss": "8.4.0"
  }
}
'''
        },
        {
            "path": "src/app/page.tsx",
            "content": '''export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-3xl font-bold">Dashboard</h1>
      <p className="mt-4 text-gray-600">Welcome to your OneDay dashboard!</p>
    </main>
  );
}
'''
        },
        {
            "path": "src/app/layout.tsx",
            "content": '''import "./globals.css";

export const metadata = {
  title: "OneDay Dashboard",
  description: "Generated by OneDay.run",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
'''
        },
        {
            "path": "src/app/globals.css",
            "content": '''@tailwind base;
@tailwind components;
@tailwind utilities;
'''
        },
        {
            "path": "tailwind.config.js",
            "content": '''module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
'''
        }
    ],
    dependencies=["next", "react", "tailwindcss"],
    env_vars=["NEXT_PUBLIC_API_URL"],
    recommended_components=["ui-react-dashboard"]
)


# Express API Template
EXPRESS_API_TEMPLATE = ProjectTemplate(
    id="express-api",
    name="Express.js API",
    description="Node.js REST API with Express",
    tech_stack="node_express",
    project_type="api",
    files=[
        {
            "path": "package.json",
            "content": '''{
  "name": "oneday-express-api",
  "version": "1.0.0",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js",
    "dev": "nodemon src/index.js"
  },
  "dependencies": {
    "express": "^4.18.2",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "helmet": "^7.1.0"
  },
  "devDependencies": {
    "nodemon": "^3.0.1"
  }
}
'''
        },
        {
            "path": "src/index.js",
            "content": '''require("dotenv").config();
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");

const app = express();
const PORT = process.env.PORT || 3000;

app.use(helmet());
app.use(cors());
app.use(express.json());

app.get("/", (req, res) => {
  res.json({ message: "OneDay Express API", version: "1.0.0" });
});

app.get("/health", (req, res) => {
  res.json({ status: "healthy" });
});

app.get("/api/items", (req, res) => {
  res.json({ items: [] });
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
'''
        },
        {
            "path": ".env.example",
            "content": '''PORT=3000
NODE_ENV=development
'''
        },
        {
            "path": ".gitignore",
            "content": '''node_modules/
.env
*.log
'''
        }
    ],
    dependencies=["express", "cors", "helmet", "dotenv"],
    env_vars=["PORT", "NODE_ENV"],
    recommended_components=[]
)


# All templates
TEMPLATES: Dict[str, ProjectTemplate] = {
    "fastapi-api": FASTAPI_API_TEMPLATE,
    "nextjs-dashboard": NEXTJS_DASHBOARD_TEMPLATE,
    "express-api": EXPRESS_API_TEMPLATE,
}


def get_template(template_id: str) -> ProjectTemplate:
    """Pobiera template po ID"""
    return TEMPLATES.get(template_id)


def get_template_for_stack(tech_stack: str, project_type: str) -> ProjectTemplate:
    """Pobiera template na podstawie stacku i typu projektu"""
    for template in TEMPLATES.values():
        if template.tech_stack == tech_stack and template.project_type == project_type:
            return template
    
    # Fallback - znajdź po samym stacku
    for template in TEMPLATES.values():
        if template.tech_stack == tech_stack:
            return template
    
    return None


def list_templates() -> List[Dict[str, Any]]:
    """Lista wszystkich template'ów"""
    return [
        {
            "id": t.id,
            "name": t.name,
            "description": t.description,
            "tech_stack": t.tech_stack,
            "project_type": t.project_type
        }
        for t in TEMPLATES.values()
    ]
